[package]
name = "web_server_rust"
version = "0.1.0"
authors = ["Fernando Marca Magalh√£es <59258828+fernandomarca@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
